//! Leptos components for flow editors

pub mod controls;
pub mod minimap;

#[cfg(test)]
pub mod tests;

use leptos::*;
use std::ops::Deref;
use wasm_bindgen::JsCast;
use web_sys::HtmlCanvasElement;

use flow_core::Graph;
use flow_renderer::traits::{BackgroundConfig, BackgroundVariant};
use flow_renderer::{Canvas2DRenderer, Renderer, RendererType};

use crate::signals::{FlowState, ViewportState};
// use crate::events::{FlowEvent, NodeEvent};
use crate::hooks::use_canvas_mouse;

// Note: FlowEditorProps is automatically generated by the #[component] macro

/// Main flow editor component
#[component]
pub fn FlowEditor<N, E>(
    /// The graph to display and edit
    graph: RwSignal<Graph<N, E>>,
    /// Canvas width
    #[prop(default = 800)]
    width: u32,
    /// Canvas height
    #[prop(default = 600)]
    height: u32,
    /// Preferred renderer type
    #[prop(optional)]
    _renderer_type: Option<RendererType>,
) -> impl IntoView
where
    N: Clone + serde::Serialize + 'static,
    E: Clone + Default + serde::Serialize + 'static,
{
    let canvas_ref = create_node_ref::<leptos::html::Canvas>();
    let viewport = create_rw_signal(ViewportState::default());
    let flow_state = create_rw_signal(FlowState::default());
    let renderer_initialized = create_rw_signal(false);

    // Initialize renderer when canvas is mounted
    create_effect(move |_| {
        if let Some(canvas_el) = canvas_ref.get_untracked() {
            let canvas_element = canvas_el
                .deref()
                .clone()
                .unchecked_into::<HtmlCanvasElement>();

            match Canvas2DRenderer::new(&canvas_element) {
                Ok(mut renderer) => {
                    // Set canvas size
                    if let Err(e) = renderer.resize(width, height) {
                        tracing::error!("Failed to resize renderer: {}", e);
                        return;
                    }

                    // Mark renderer as initialized
                    renderer_initialized.set(true);
                    tracing::info!("Renderer initialized successfully");
                }
                Err(e) => {
                    tracing::error!("Failed to create renderer: {}", e);
                }
            }
        }
    });

    // Render loop effect
    create_effect(move |_| {
        let graph_val = graph.get();
        let viewport_val = viewport.get();

        if renderer_initialized.get() {
            if let Some(canvas_el) = canvas_ref.get_untracked() {
                let canvas_element = canvas_el
                    .deref()
                    .clone()
                    .unchecked_into::<HtmlCanvasElement>();

                // Create a new renderer for each render (not ideal, but works for demo)
                if let Ok(mut renderer) = Canvas2DRenderer::new(&canvas_element) {
                    // Set canvas size
                    if let Err(e) = renderer.resize(width, height) {
                        tracing::error!("Failed to resize renderer: {}", e);
                        return;
                    }

                    // Clear the canvas
                    if let Err(e) = renderer.clear(Some("#f8f9fa")) {
                        tracing::error!("Failed to clear renderer: {}", e);
                        return;
                    }

                    // Set viewport
                    renderer.set_viewport(&viewport_val.viewport);

                    // Render background
                    let bg_config = BackgroundConfig {
                        variant: BackgroundVariant::Dots,
                        color: "#f8f9fa".to_string(),
                        pattern_color: "#e9ecef".to_string(),
                        size: 20.0,
                        opacity: 0.5,
                    };

                    if let Err(e) = renderer.render_background(&bg_config, &viewport_val.viewport) {
                        tracing::error!("Failed to render background: {}", e);
                    }

                    // Render the graph with selection state
                    let flow_state_val = flow_state.get();
                    match renderer.render_graph_with_selection_dyn(
                        &graph_val,
                        &viewport_val.viewport,
                        &flow_state_val.selected_nodes,
                    ) {
                        Ok(stats) => {
                            tracing::debug!(
                                "Rendered graph: {} nodes, {} edges, {:.2}ms",
                                stats.nodes_rendered,
                                stats.edges_rendered,
                                stats.frame_time_ms
                            );

                            // Update flow state with render stats
                            flow_state.update(|state| {
                                state.render_stats = Some(stats);
                            });
                        }
                        Err(e) => {
                            tracing::error!("Failed to render graph: {}", e);
                        }
                    }

                    // Present the frame
                    if let Err(e) = renderer.present() {
                        tracing::error!("Failed to present frame: {}", e);
                    }
                }
            }
        }
    });

    // Set up mouse interactions
    use_canvas_mouse(
        canvas_ref, graph, viewport, flow_state, None, // on_flow_event
        None, // on_node_event
    );

    view! {
        <div class="flow-editor" style="position: relative; border: 1px solid #ddd; background: #f8f9fa;">
            <canvas
                node_ref=canvas_ref
                width=width
                height=height
                class="flow-canvas"
                style=format!("width: {}px; height: {}px; display: block;", width, height)
            />
            <FlowStats flow_state=flow_state.read_only() />
        </div>
    }
}

/// Simple flow canvas component for basic use cases
#[component]
pub fn FlowCanvas<N, E>(
    /// The graph to display
    graph: ReadSignal<Graph<N, E>>,
    /// Canvas width
    #[prop(default = 400)]
    width: u32,
    /// Canvas height
    #[prop(default = 300)]
    height: u32,
) -> impl IntoView
where
    N: Clone + serde::Serialize + 'static,
    E: Clone + Default + serde::Serialize + 'static,
{
    let graph_rw = create_rw_signal(graph.get());

    // Keep graph_rw in sync with the read signal
    create_effect(move |_| {
        graph_rw.set(graph.get());
    });

    view! {
        <FlowEditor
            graph=graph_rw
            width=width
            height=height
        />
    }
}

/// Performance statistics display component
#[component]
pub fn FlowStats(
    /// Flow state containing render stats
    flow_state: ReadSignal<FlowState>,
) -> impl IntoView {
    view! {
        <div class="flow-stats" style="position: absolute; top: 10px; right: 10px; background: rgba(255,255,255,0.9); padding: 8px; border-radius: 4px; font-size: 12px; font-family: monospace; box-shadow: 0 2px 4px rgba(0,0,0,0.1);">
            {move || {
                if let Some(stats) = &flow_state.get().render_stats {
                    view! {
                        <div class="stats-grid" style="display: grid; grid-template-columns: auto auto; gap: 4px;">
                            <div class="stat-item">
                                <span class="stat-label">"Frame:"</span>
                                <span class="stat-value">{format!("{:.1}ms", stats.frame_time_ms)}</span>
                            </div>
                            <div class="stat-item">
                                <span class="stat-label">"Nodes:"</span>
                                <span class="stat-value">{stats.nodes_rendered}</span>
                            </div>
                            <div class="stat-item">
                                <span class="stat-label">"Edges:"</span>
                                <span class="stat-value">{stats.edges_rendered}</span>
                            </div>
                            <div class="stat-item">
                                <span class="stat-label">"Draws:"</span>
                                <span class="stat-value">{stats.draw_calls}</span>
                            </div>
                        </div>
                    }.into_view()
                } else {
                    view! {
                        <div class="no-stats">"Initializing..."</div>
                    }.into_view()
                }
            }}
        </div>
    }
}

// Tests are in the tests/ subdirectory
