//! Leptos components for flow editors

pub mod controls;
pub mod minimap;

#[cfg(test)]
pub mod tests;

use leptos::prelude::*;
// use leptos::html::Canvas; // Unused import
use std::ops::Deref;
use wasm_bindgen::JsCast;
use web_sys::HtmlCanvasElement;

// use flow_rs_core::Graph; // Unused import
use flow_rs_renderer::traits::{BackgroundConfig, BackgroundVariant};
use flow_rs_renderer::{Canvas2DRenderer, Renderer, RendererType};

use crate::signals::{FlowState, ViewportState};
// use crate::events::{FlowEvent, NodeEvent};
use crate::hooks::use_canvas_mouse_simplified;
use crate::signals::FlowSignalManager;

// Note: FlowEditorProps is automatically generated by the #[component] macro

/// Main flow editor component
#[component]
pub fn FlowEditor(
    /// Canvas width
    #[prop(default = 800)]
    width: u32,
    /// Canvas height
    #[prop(default = 600)]
    height: u32,
    /// Preferred renderer type
    #[prop(optional)]
    _renderer_type: Option<RendererType>,
) -> impl IntoView
{
    let canvas_ref: NodeRef<leptos::html::Canvas> = NodeRef::new();
    let viewport = RwSignal::new(ViewportState::default());
    let flow_state = RwSignal::new(FlowState::default());
    let renderer_initialized = RwSignal::new(false);

    // Initialize renderer when canvas is mounted
    Effect::new(move |_| {
        if let Some(canvas_el) = canvas_ref.get_untracked() {
            // Use explicit type annotation to resolve type inference
            let canvas_element: web_sys::HtmlCanvasElement = canvas_el
                .deref()
                .clone()
                .unchecked_into();

            match Canvas2DRenderer::new(&canvas_element) {
                Ok(mut renderer) => {
                    // Set canvas size
                    if let Err(e) = renderer.resize(width, height) {
                        tracing::error!("Failed to resize renderer: {}", e);
                        return;
                    }

                    // Mark renderer as initialized
                    renderer_initialized.set(true);
                    tracing::info!("Renderer initialized successfully");
                }
                Err(e) => {
                    tracing::error!("Failed to create renderer: {}", e);
                }
            }
        }
    });

    // Create signal manager
    let signal_manager = FlowSignalManager::new();
    
    // Render loop effect
    Effect::new(move |_| {
        let graph_val = signal_manager.get_graph();
        let viewport_val = viewport.get();

        if renderer_initialized.get() {
            if let Some(canvas_el) = canvas_ref.get_untracked() {
                let canvas_element = canvas_el
                    .deref()
                    .clone()
                    .unchecked_into::<HtmlCanvasElement>();

                // Create a new renderer for each render (not ideal, but works for demo)
                if let Ok(mut renderer) = Canvas2DRenderer::new(&canvas_element) {
                    // Set canvas size
                    if let Err(e) = renderer.resize(width, height) {
                        tracing::error!("Failed to resize renderer: {}", e);
                        return;
                    }

                    // Clear the canvas
                    if let Err(e) = renderer.clear(Some("#f8f9fa")) {
                        tracing::error!("Failed to clear renderer: {}", e);
                        return;
                    }

                    // Set viewport
                    renderer.set_viewport(&viewport_val.viewport);

                    // Render background
                    let bg_config = BackgroundConfig {
                        variant: BackgroundVariant::Dots,
                        color: "#f8f9fa".to_string(),
                        pattern_color: "#e9ecef".to_string(),
                        size: 20.0,
                        opacity: 0.5,
                    };

                    if let Err(e) = renderer.render_background(&bg_config, &viewport_val.viewport) {
                        tracing::error!("Failed to render background: {}", e);
                    }

                    // Render the graph with selection state
                    let flow_state_val = flow_state.get();
                    match renderer.render_graph_with_selection_dyn(
                        &graph_val,
                        &viewport_val.viewport,
                        &flow_state_val.selected_nodes,
                    ) {
                        Ok(stats) => {
                            tracing::debug!(
                                "Rendered graph: {} nodes, {} edges, {:.2}ms",
                                stats.nodes_rendered,
                                stats.edges_rendered,
                                stats.frame_time_ms
                            );

                            // Update flow state with render stats
                            flow_state.update(|state| {
                                state.render_stats = Some(stats);
                            });
                        }
                        Err(e) => {
                            tracing::error!("Failed to render graph: {}", e);
                        }
                    }

                    // Present the frame
                    if let Err(e) = renderer.present() {
                        tracing::error!("Failed to present frame: {}", e);
                    }
                }
            }
        }
    });

    // Create signal manager
    let signal_manager = FlowSignalManager::new();
    
    // Set up mouse interactions with simplified function
    use_canvas_mouse_simplified(
        canvas_ref, 
        signal_manager, 
        None, // on_flow_event
    );

    view! {
        <div class="flow-editor" style="position: relative; border: 1px solid #ddd; background: #f8f9fa;">
            <canvas
                node_ref=canvas_ref
                width=width
                height=height
                class="flow-canvas"
                style=format!("width: {}px; height: {}px; display: block;", width, height)
            />
            <FlowStats flow_state=flow_state.read_only() />
        </div>
    }
}

/// Simple flow canvas component for basic use cases
#[component]
pub fn FlowCanvas(
    /// Canvas width
    #[prop(default = 400)]
    width: u32,
    /// Canvas height
    #[prop(default = 300)]
    height: u32,
) -> impl IntoView
{
    let signal_manager = FlowSignalManager::new();

    view! {
        <FlowEditor
            width=width
            height=height
        />
    }
}

/// Performance statistics display component
#[component]
pub fn FlowStats(
    /// Flow state containing render stats
    flow_state: ReadSignal<FlowState>,
) -> impl IntoView {
    view! {
        <div class="flow-stats" style="position: absolute; top: 10px; right: 10px; background: rgba(255,255,255,0.9); padding: 8px; border-radius: 4px; font-size: 12px; font-family: monospace; box-shadow: 0 2px 4px rgba(0,0,0,0.1);">
            <div class="stats-container" style="display: block;">
                <div class="stats-grid" style="display: grid; grid-template-columns: auto auto; gap: 4px;">
                    <div class="stat-item">
                        <span class="stat-label">"Frame:"</span>
                        <span class="stat-value">{move || if let Some(stats) = &flow_state.get().render_stats { format!("{:.1}ms", stats.frame_time_ms) } else { "N/A".to_string() }}</span>
                    </div>
                    <div class="stat-item">
                        <span class="stat-label">"Nodes:"</span>
                        <span class="stat-value">{move || if let Some(stats) = &flow_state.get().render_stats { stats.nodes_rendered.to_string() } else { "N/A".to_string() }}</span>
                    </div>
                    <div class="stat-item">
                        <span class="stat-label">"Edges:"</span>
                        <span class="stat-value">{move || if let Some(stats) = &flow_state.get().render_stats { stats.edges_rendered.to_string() } else { "N/A".to_string() }}</span>
                    </div>
                    <div class="stat-item">
                        <span class="stat-label">"Draws:"</span>
                        <span class="stat-value">{move || if let Some(stats) = &flow_state.get().render_stats { stats.draw_calls.to_string() } else { "N/A".to_string() }}</span>
                    </div>
                </div>
            </div>
        </div>
    }
}

// Tests are in the tests/ subdirectory
