//! Leptos components for flow editors

pub mod controls;
pub mod minimap;

#[cfg(test)]
pub mod tests;

use leptos::prelude::*;
use std::ops::Deref;
use wasm_bindgen::JsCast;
use web_sys::HtmlCanvasElement;

use flow_rs_renderer::traits::{BackgroundConfig, BackgroundVariant};
use flow_rs_renderer::{Canvas2DRenderer, Renderer, RendererType};

use crate::signals::{FlowState, ViewportState};
use crate::hooks::use_canvas_mouse_simplified;
use crate::signals::FlowSignalManager;
use crate::accessibility::{
    AccessibilityConfig, AriaAttributes, AriaRole, FocusManager,
    KeyboardNavigation, ScreenReader, create_accessible_keyboard_handler
};
use crate::touch::{use_touch_gestures, TouchUIUtils};
use crate::selection::use_selection;
use crate::context_menu::use_context_menu;
use crate::keyboard_shortcuts::use_keyboard_shortcuts;
use crate::history::{HistoryManager, ClipboardManager};
use flow_rs_core::{Graph, Size, Position};
use std::collections::HashSet;

// Note: FlowEditorProps is automatically generated by the #[component] macro

/// Main flow editor component with full professional UX support
#[component]
pub fn FlowEditor(
    /// Canvas width
    #[prop(default = 800)]
    width: u32,
    /// Canvas height
    #[prop(default = 600)]
    height: u32,
    /// Preferred renderer type
    #[prop(optional)]
    _renderer_type: Option<RendererType>,
    /// Accessibility configuration
    #[prop(default = AccessibilityConfig::default())]
    accessibility: AccessibilityConfig,
    /// Enable touch gestures for mobile devices
    #[prop(default = true)]
    enable_touch: bool,
    /// Touch event throttling (ms)
    #[prop(default = 16.0)]
    touch_throttle_ms: f64,
    /// Enable node resizing
    #[prop(default = true)]
    enable_node_resizing: bool,
    /// Enable multi-selection
    #[prop(default = true)]
    enable_selection: bool,
    /// Enable context menus
    #[prop(default = true)]
    enable_context_menu: bool,
    /// Enable keyboard shortcuts
    #[prop(default = true)]
    enable_keyboard_shortcuts: bool,
    /// Enable undo/redo
    #[prop(default = true)]
    enable_history: bool,
) -> impl IntoView
{
    let canvas_ref: NodeRef<leptos::html::Canvas> = NodeRef::new();
    let viewport = RwSignal::new(ViewportState::default());
    let flow_state = RwSignal::new(FlowState::default());
    let renderer_initialized = RwSignal::new(false);

    // Advanced UX state
    let history_manager = RwSignal::new(HistoryManager::new());
    let clipboard_manager = RwSignal::new(ClipboardManager::new());

    // Accessibility state
    let keyboard_nav = RwSignal::new(KeyboardNavigation::new());
    let screen_reader = RwSignal::new(ScreenReader::new());
    let focus_manager = RwSignal::new(FocusManager::new());

    // Initialize renderer when canvas is mounted
    Effect::new(move |_| {
        if let Some(canvas_el) = canvas_ref.get_untracked() {
            // Use explicit type annotation to resolve type inference
            let canvas_element: web_sys::HtmlCanvasElement = canvas_el
                .deref()
                .clone()
                .unchecked_into();

            match Canvas2DRenderer::new(&canvas_element) {
                Ok(mut renderer) => {
                    // Set canvas size
                    if let Err(e) = renderer.resize(width, height) {
                        tracing::error!("Failed to resize renderer: {}", e);
                        return;
                    }

                    // Mark renderer as initialized
                    renderer_initialized.set(true);
                    tracing::info!("Renderer initialized successfully");
                }
                Err(e) => {
                    tracing::error!("Failed to create renderer: {}", e);
                }
            }
        }
    });

    // Create signal manager
    let signal_manager = FlowSignalManager::new();
    
    // Render loop effect
    Effect::new(move |_| {
        let graph_val = signal_manager.get_graph();
        let viewport_val = viewport.get();

        if renderer_initialized.get() {
            if let Some(canvas_el) = canvas_ref.get_untracked() {
                let canvas_element = canvas_el
                    .deref()
                    .clone()
                    .unchecked_into::<HtmlCanvasElement>();

                // Create a new renderer for each render (not ideal, but works for demo)
                if let Ok(mut renderer) = Canvas2DRenderer::new(&canvas_element) {
                    // Set canvas size
                    if let Err(e) = renderer.resize(width, height) {
                        tracing::error!("Failed to resize renderer: {}", e);
                        return;
                    }

                    // Clear the canvas
                    if let Err(e) = renderer.clear(Some("#f8f9fa")) {
                        tracing::error!("Failed to clear renderer: {}", e);
                        return;
                    }

                    // Set viewport
                    renderer.set_viewport(&viewport_val.viewport);

                    // Render background
                    let bg_config = BackgroundConfig {
                        variant: BackgroundVariant::Dots,
                        color: "#f8f9fa".to_string(),
                        pattern_color: "#e9ecef".to_string(),
                        size: 20.0,
                        opacity: 0.5,
                    };

                    if let Err(e) = renderer.render_background(&bg_config, &viewport_val.viewport) {
                        tracing::error!("Failed to render background: {}", e);
                    }

                    // Render the graph with selection state
                    let flow_state_val = flow_state.get();
                    match renderer.render_graph_with_selection_dyn(
                        &graph_val,
                        &viewport_val.viewport,
                        &flow_state_val.selected_nodes,
                    ) {
                        Ok(stats) => {
                            tracing::debug!(
                                "Rendered graph: {} nodes, {} edges, {:.2}ms",
                                stats.nodes_rendered,
                                stats.edges_rendered,
                                stats.frame_time_ms
                            );

                            // Update flow state with render stats
                            flow_state.update(|state| {
                                state.render_stats = Some(stats);
                            });
                        }
                        Err(e) => {
                            tracing::error!("Failed to render graph: {}", e);
                        }
                    }

                    // Present the frame
                    if let Err(e) = renderer.present() {
                        tracing::error!("Failed to present frame: {}", e);
                    }
                }
            }
        }
    });

    // Create signal manager
    let signal_manager = FlowSignalManager::new();

    // Set up mouse interactions with simplified function
    use_canvas_mouse_simplified(
        canvas_ref,
        signal_manager.clone(),
        None, // on_flow_event
    );

    // Set up accessible keyboard navigation
    let accessible_keyboard_handler = create_accessible_keyboard_handler(
        keyboard_nav,
        screen_reader,
    );

    // Register canvas for keyboard navigation
    keyboard_nav.update(|nav| {
        nav.register_element("flow-canvas".to_string());
    });

    // Set up touch gestures for mobile devices
    if enable_touch && TouchUIUtils::is_touch_device() {
        let _touch_cleanup = use_touch_gestures(
            canvas_ref,
            flow_state,
            viewport,
            touch_throttle_ms,
        );
    }

    // Set up node resizing
    if enable_node_resizing {
        // Note: Node resizing integration would go here
        // For now, the infrastructure is in place but needs integration
        // with the existing graph management system
    }

    // Advanced UX features - simplified for now
    // TODO: Implement full integration of selection, context menus, and keyboard shortcuts

    // Generate ARIA labels and descriptions
    let canvas_aria_label = move || {
        let flow_state_val = flow_state.get();
        let graph = signal_manager.get_graph();
        AriaAttributes::canvas_live_region(
            graph.nodes().count(),
            graph.edges().count(),
            flow_state_val.selected_nodes.len()
        )
    };

    // Calculate touch-friendly dimensions
    let touch_friendly_width = if TouchUIUtils::is_touch_device() {
        (width as f64 * 1.2).min(1200.0) as u32 // Slightly larger on touch devices
    } else {
        width
    };

    let touch_friendly_height = if TouchUIUtils::is_touch_device() {
        (height as f64 * 1.2).min(800.0) as u32
    } else {
        height
    };

    view! {
        <div
            class="flow-editor"
            class:touch-device=TouchUIUtils::is_touch_device()
            style=move || format!(
                "position: relative; border: 1px solid #ddd; background: #f8f9fa; touch-action: none; {}",
                if TouchUIUtils::is_touch_device() {
                    "padding: 10px;"
                } else {
                    ""
                }
            )
            role=AriaRole::Application.as_str()
            attr:aria-label="Flow editor canvas"
            attr:aria-describedby="flow-stats"
        >
            <canvas
                node_ref=canvas_ref
                id="flow-canvas"
                width=touch_friendly_width
                height=touch_friendly_height
                class="flow-canvas"
                class:touch-canvas=TouchUIUtils::is_touch_device()
                style=move || format!(
                    "width: {}px; height: {}px; display: block; touch-action: none; {}",
                    touch_friendly_width,
                    touch_friendly_height,
                    if TouchUIUtils::is_touch_device() {
                        "border-radius: 8px; box-shadow: 0 4px 12px rgba(0,0,0,0.1);"
                    } else {
                        ""
                    }
                )
                role=AriaRole::Img.as_str()
                attr:aria-label=canvas_aria_label
                tabindex="0"
                on:keydown=move |e| accessible_keyboard_handler(e)
            />
            <FlowStats
                flow_state=flow_state.read_only()
                _accessibility=accessibility.clone()
            />
        </div>
    }
}

/// Simple flow canvas component for basic use cases with full professional UX support
#[component]
pub fn FlowCanvas(
    /// Canvas width
    #[prop(default = 400)]
    width: u32,
    /// Canvas height
    #[prop(default = 300)]
    height: u32,
    /// Accessibility configuration
    #[prop(default = AccessibilityConfig::default())]
    accessibility: AccessibilityConfig,
    /// Enable touch gestures for mobile devices
    #[prop(default = true)]
    enable_touch: bool,
    /// Touch event throttling (ms)
    #[prop(default = 16.0)]
    touch_throttle_ms: f64,
    /// Enable node resizing
    #[prop(default = true)]
    enable_node_resizing: bool,
    /// Enable multi-selection
    #[prop(default = true)]
    enable_selection: bool,
    /// Enable context menus
    #[prop(default = true)]
    enable_context_menu: bool,
    /// Enable keyboard shortcuts
    #[prop(default = true)]
    enable_keyboard_shortcuts: bool,
    /// Enable undo/redo
    #[prop(default = true)]
    enable_history: bool,
) -> impl IntoView
{
    let _signal_manager = FlowSignalManager::new();

    view! {
        <FlowEditor
            width=width
            height=height
            accessibility=accessibility
            enable_touch=enable_touch
            touch_throttle_ms=touch_throttle_ms
            enable_node_resizing=enable_node_resizing
            enable_selection=enable_selection
            enable_context_menu=enable_context_menu
            enable_keyboard_shortcuts=enable_keyboard_shortcuts
            enable_history=enable_history
        />
    }
}

/// Performance statistics display component with accessibility support
#[component]
pub fn FlowStats(
    /// Flow state containing render stats
    flow_state: ReadSignal<FlowState>,
    /// Accessibility configuration
    #[prop(default = AccessibilityConfig::default())]
    _accessibility: AccessibilityConfig,
) -> impl IntoView {
    view! {
        <div
            id="flow-stats"
            class="flow-stats"
            style="position: absolute; top: 10px; right: 10px; background: rgba(255,255,255,0.9); padding: 8px; border-radius: 4px; font-size: 12px; font-family: monospace; box-shadow: 0 2px 4px rgba(0,0,0,0.1);"
            role=AriaRole::Region.as_str()
            attr:aria-label="Flow editor performance statistics"
            attr:aria-live="polite"
        >
            <div class="stats-container" style="display: block;">
                <div class="stats-grid" style="display: grid; grid-template-columns: auto auto; gap: 4px;">
                    <div class="stat-item">
                        <span class="stat-label">"Frame:"</span>
                        <span class="stat-value">{move || if let Some(stats) = &flow_state.get().render_stats { format!("{:.1}ms", stats.frame_time_ms) } else { "N/A".to_string() }}</span>
                    </div>
                    <div class="stat-item">
                        <span class="stat-label">"Nodes:"</span>
                        <span class="stat-value">{move || if let Some(stats) = &flow_state.get().render_stats { stats.nodes_rendered.to_string() } else { "N/A".to_string() }}</span>
                    </div>
                    <div class="stat-item">
                        <span class="stat-label">"Edges:"</span>
                        <span class="stat-value">{move || if let Some(stats) = &flow_state.get().render_stats { stats.edges_rendered.to_string() } else { "N/A".to_string() }}</span>
                    </div>
                    <div class="stat-item">
                        <span class="stat-label">"Draws:"</span>
                        <span class="stat-value">{move || if let Some(stats) = &flow_state.get().render_stats { stats.draw_calls.to_string() } else { "N/A".to_string() }}</span>
                    </div>
                </div>
            </div>
        </div>
    }
}

// Tests are in the tests/ subdirectory
