//! MiniMap component for flow editor
//!
//! Provides a miniature overview of the entire flow graph with viewport indicator.

use leptos::*;
use wasm_bindgen::JsCast;
use std::ops::Deref;
use web_sys::{CanvasRenderingContext2d, Element, HtmlCanvasElement, HtmlElement, MouseEvent};

use flow_core::{Graph, Position, Viewport, Node, Edge};
use flow_renderer::Canvas2DRenderer;
use crate::signals::{FlowState, ViewportState};

/// Configuration for the MiniMap component
#[derive(Debug, Clone)]
pub struct MiniMapConfig {
    /// Width of the minimap in pixels
    pub width: f64,
    /// Height of the minimap in pixels
    pub height: f64,
    /// Background color
    pub background_color: String,
    /// Border color
    pub border_color: String,
    /// Viewport indicator color
    pub viewport_color: String,
    /// Node color in minimap
    pub node_color: String,
    /// Edge color in minimap
    pub edge_color: String,
    /// Scale factor for minimap (smaller = more zoomed out)
    pub scale_factor: f64,
}

impl Default for MiniMapConfig {
    fn default() -> Self {
        Self {
            width: 200.0,
            height: 150.0,
            background_color: "#f8f9fa".to_string(),
            border_color: "#dee2e6".to_string(),
            viewport_color: "#007bff".to_string(),
            node_color: "#6c757d".to_string(),
            edge_color: "#adb5bd".to_string(),
            scale_factor: 0.1,
        }
    }
}

// Note: MiniMapProps is automatically generated by the #[component] macro

/// MiniMap component for graph overview
#[component]
pub fn MiniMap<N, E>(
    /// Flow graph
    graph: ReadSignal<Graph<N, E>>,
    /// Viewport state
    viewport: ReadSignal<ViewportState>,
    /// MiniMap configuration
    #[prop(default = MiniMapConfig::default())]
    config: MiniMapConfig,
    /// Optional viewport change handler
    #[prop(optional)]
    on_viewport_change: Option<WriteSignal<Position>>,
) -> impl IntoView
where
    N: Clone + 'static,
    E: Clone + 'static,
{
    let canvas_ref = create_node_ref::<leptos::html::Canvas>();
    let config_clone = config.clone();

    // Render effect that updates the minimap when graph or viewport changes
    create_effect(move |_| {
        let graph_value = graph.get();
        let viewport_value = viewport.get();

        if let Some(canvas_element) = canvas_ref.get_untracked() {
            render_minimap(&canvas_element, &graph_value, &viewport_value, &config_clone);
        }
    });

    // Handle click events for viewport navigation
    let on_click = {
        let config = config.clone();
        move |event: MouseEvent| {
            if let Some(handler) = on_viewport_change {
                if let Some(canvas) = canvas_ref.get_untracked() {
                    let canvas_element = canvas.deref().clone().unchecked_into::<HtmlCanvasElement>();
                    // Use proper DOM rect access with mouse integration
                    let mut rect_utils = crate::dom_rect::DomRectUtils::new();
                    let canvas_pos = crate::mouse_integration::utils::mouse_event_to_canvas_coords(
                        &event,
                        &canvas_element,
                        &mut rect_utils,
                    ).unwrap_or_else(|_| {
                        // Fallback to simple calculation if DOM rect access fails
                        Position::new(
                            event.client_x() as f64,
                            event.client_y() as f64,
                        )
                    });
                    let x = canvas_pos.x;
                    let y = canvas_pos.y;

                    // Convert minimap coordinates to world coordinates
                    let world_pos = minimap_to_world_coords(
                        Position::new(x, y),
                        &config,
                        &graph.get_untracked(),
                    );

                    handler.set(world_pos);
                }
            }
        }
    };

    view! {
        <div class="minimap-container" style=format!(
            "width: {}px; height: {}px; border: 1px solid {}; background: {};",
            config.width, config.height, config.border_color, config.background_color
        )>
            <canvas
                node_ref=canvas_ref
                width=config.width as u32
                height=config.height as u32
                style="display: block; cursor: pointer;"
                on:click=on_click
            />
        </div>
    }
}

/// Render the minimap content
fn render_minimap<N: Clone, E: Clone>(
    canvas: &leptos::HtmlElement<leptos::html::Canvas>,
    graph: &Graph<N, E>,
    viewport_state: &ViewportState,
    config: &MiniMapConfig,
) {
    // Get the underlying HtmlCanvasElement
    let canvas_element = canvas.deref().clone().unchecked_into::<HtmlCanvasElement>();
    let context = canvas_element
        .get_context("2d")
        .unwrap()
        .unwrap()
        .dyn_into::<CanvasRenderingContext2d>()
        .unwrap();

    // Clear canvas
    context.clear_rect(0.0, 0.0, config.width, config.height);

    // Calculate graph bounds
    let bounds = calculate_graph_bounds(graph);
    if bounds.is_none() {
        return; // Empty graph
    }
    let bounds = bounds.unwrap();

    // Calculate scale to fit graph in minimap
    let scale_x = config.width / bounds.width;
    let scale_y = config.height / bounds.height;
    let scale = scale_x.min(scale_y) * config.scale_factor;

    // Center the graph in the minimap
    let offset_x = (config.width - bounds.width * scale) / 2.0 - bounds.x * scale;
    let offset_y = (config.height - bounds.height * scale) / 2.0 - bounds.y * scale;

    // Render edges
    context.set_stroke_style(&config.edge_color.clone().into());
    context.set_line_width(1.0);
    context.begin_path();

    for edge in graph.edges() {
        if let (Some(source), Some(target)) = (graph.get_node(&edge.source), graph.get_node(&edge.target)) {
            let start_x = source.position.x * scale + offset_x;
            let start_y = source.position.y * scale + offset_y;
            let end_x = target.position.x * scale + offset_x;
            let end_y = target.position.y * scale + offset_y;

            context.move_to(start_x, start_y);
            context.line_to(end_x, end_y);
        }
    }
    context.stroke();

    // Render nodes
    context.set_fill_style(&config.node_color.clone().into());
    for node in graph.nodes() {
        let x = node.position.x * scale + offset_x;
        let y = node.position.y * scale + offset_y;
        let width = node.size.width * scale;
        let height = node.size.height * scale;

        context.fill_rect(x - width/2.0, y - height/2.0, width, height);
    }

    // Render viewport indicator
    context.set_stroke_style(&config.viewport_color.clone().into());
    context.set_line_width(2.0);

    let viewport = &viewport_state.viewport;
    let viewport_x = viewport.x * scale + offset_x;
    let viewport_y = viewport.y * scale + offset_y;
    let viewport_width = viewport.width * scale / viewport.zoom;
    let viewport_height = viewport.height * scale / viewport.zoom;

    context.stroke_rect(viewport_x, viewport_y, viewport_width, viewport_height);
}

/// Calculate the bounding box of all nodes in the graph
fn calculate_graph_bounds<N, E>(graph: &Graph<N, E>) -> Option<Bounds> {
    if graph.nodes().count() == 0 {
        return None;
    }

    let mut min_x = f64::INFINITY;
    let mut min_y = f64::INFINITY;
    let mut max_x = f64::NEG_INFINITY;
    let mut max_y = f64::NEG_INFINITY;

    for node in graph.nodes() {
        let left = node.position.x - node.size.width / 2.0;
        let right = node.position.x + node.size.width / 2.0;
        let top = node.position.y - node.size.height / 2.0;
        let bottom = node.position.y + node.size.height / 2.0;

        min_x = min_x.min(left);
        min_y = min_y.min(top);
        max_x = max_x.max(right);
        max_y = max_y.max(bottom);
    }

    Some(Bounds {
        x: min_x,
        y: min_y,
        width: max_x - min_x,
        height: max_y - min_y,
    })
}

/// Convert minimap coordinates to world coordinates
fn minimap_to_world_coords<N, E>(
    minimap_pos: Position,
    config: &MiniMapConfig,
    graph: &Graph<N, E>,
) -> Position {
    let bounds = calculate_graph_bounds(graph);
    if bounds.is_none() {
        return Position::zero();
    }
    let bounds = bounds.unwrap();

    let scale_x = config.width / bounds.width;
    let scale_y = config.height / bounds.height;
    let scale = scale_x.min(scale_y) * config.scale_factor;

    let offset_x = (config.width - bounds.width * scale) / 2.0 - bounds.x * scale;
    let offset_y = (config.height - bounds.height * scale) / 2.0 - bounds.y * scale;

    let world_x = (minimap_pos.x - offset_x) / scale;
    let world_y = (minimap_pos.y - offset_y) / scale;

    Position::new(world_x, world_y)
}

/// Bounding box for graph bounds calculation
#[derive(Debug, Clone, Copy)]
struct Bounds {
    x: f64,
    y: f64,
    width: f64,
    height: f64,
}

#[cfg(test)]
mod tests {
    use super::*;
    use flow_core::prelude::{NodeBuilder, EdgeBuilder};

    fn create_test_graph() -> Graph<(), ()> {
        let mut graph: Graph<(), ()> = Graph::new();

        graph.add_node(NodeBuilder::<()>::new("node1")
            .position(0.0, 0.0)
            .size(100.0, 50.0)
            .build()).unwrap();

        graph.add_node(NodeBuilder::<()>::new("node2")
            .position(200.0, 100.0)
            .size(100.0, 50.0)
            .build()).unwrap();

        graph.add_edge(EdgeBuilder::new()
            .connect("node1", "node2")
            .build()
            .unwrap()).unwrap();

        graph
    }

    #[test]
    fn test_minimap_config_default() {
        let config = MiniMapConfig::default();
        assert_eq!(config.width, 200.0);
        assert_eq!(config.height, 150.0);
        assert_eq!(config.scale_factor, 0.1);
        assert_eq!(config.background_color, "#f8f9fa");
        assert_eq!(config.viewport_color, "#007bff");
    }

    #[test]
    fn test_calculate_graph_bounds_empty() {
        let graph: Graph<(), ()> = Graph::new();
        let bounds = calculate_graph_bounds(&graph);
        assert!(bounds.is_none());
    }

    #[test]
    fn test_calculate_graph_bounds() {
        let graph = create_test_graph();
        let bounds = calculate_graph_bounds(&graph).unwrap();

        // Node1: center (0,0), size 100x50 -> bounds (-50,-25) to (50,25)
        // Node2: center (200,100), size 100x50 -> bounds (150,75) to (250,125)
        // Total bounds: (-50,-25) to (250,125) -> width=300, height=150

        assert_eq!(bounds.x, -50.0);
        assert_eq!(bounds.y, -25.0);
        assert_eq!(bounds.width, 300.0);
        assert_eq!(bounds.height, 150.0);
    }

    #[test]
    fn test_minimap_to_world_coords() {
        let graph = create_test_graph();
        let config = MiniMapConfig::default();

        // Test center of minimap maps to center of graph bounds
        let center_minimap = Position::new(config.width / 2.0, config.height / 2.0);
        let world_pos = minimap_to_world_coords(center_minimap, &config, &graph);

        // Should map to approximately the center of graph bounds
        let bounds = calculate_graph_bounds(&graph).unwrap();
        let expected_center_x = bounds.x + bounds.width / 2.0;
        let expected_center_y = bounds.y + bounds.height / 2.0;

        assert!((world_pos.x - expected_center_x).abs() < 1.0);
        assert!((world_pos.y - expected_center_y).abs() < 1.0);
    }

    #[test]
    fn test_minimap_config_builder_pattern() {
        let config = MiniMapConfig {
            width: 300.0,
            height: 200.0,
            scale_factor: 0.15,
            background_color: "#ffffff".to_string(),
            viewport_color: "#ff0000".to_string(),
            ..Default::default()
        };

        assert_eq!(config.width, 300.0);
        assert_eq!(config.height, 200.0);
        assert_eq!(config.scale_factor, 0.15);
        assert_eq!(config.background_color, "#ffffff");
        assert_eq!(config.viewport_color, "#ff0000");
        // Other fields should use defaults
        assert_eq!(config.border_color, "#dee2e6");
        assert_eq!(config.node_color, "#6c757d");
    }

    #[test]
    fn test_bounds_calculation_single_node() {
        let mut graph: Graph<(), ()> = Graph::new();
        graph.add_node(NodeBuilder::<()>::new("single")
            .position(100.0, 50.0)
            .size(80.0, 40.0)
            .build()).unwrap();

        let bounds = calculate_graph_bounds(&graph).unwrap();

        // Node at (100,50) with size 80x40
        // Bounds: (60,30) to (140,70) -> width=80, height=40
        assert_eq!(bounds.x, 60.0);
        assert_eq!(bounds.y, 30.0);
        assert_eq!(bounds.width, 80.0);
        assert_eq!(bounds.height, 40.0);
    }
}
