[package]
name = "leptos-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
leptos = { version = "0.8.9", features = ["csr"] }
flow-rs-core = { path = "../../flow-core" }
flow-rs-leptos = { path = "../../flow-leptos" }
flow-rs-renderer = { path = "../../flow-renderer" }
console_error_panic_hook = "0.1"
